name: CI Pipeline - Multi-Stack (Strict Mode)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  # 全局配置
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'
  DOTNET_VERSION: '8.0'

jobs:
  # ===== 後端 Python + FastAPI =====
  backend-python:
    runs-on: ubuntu-latest
    name: "Backend (Python)"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      # Step 1: 安裝依賴
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/python/requirements.txt
          pip install pytest pytest-cov ruff pyright black bandit
      
      # Step 2: 代碼格式檢查 (Black)
      - name: Check code formatting (Black)
        run: |
          black --check src/backend/python --diff
        continue-on-error: false
      
      # Step 3: Lint 檢查 (Ruff) - Strict Mode: error 阻止
      - name: Lint check (Ruff) - Strict
        run: |
          ruff check src/backend/python
        continue-on-error: false
      
      # Step 4: 類型檢查 (Pyright)
      - name: Type check (Pyright) - Strict
        run: |
          pyright src/backend/python --warnings
        continue-on-error: false
      
      # Step 5: 單元測試 + 覆蓋率
      - name: Run tests with coverage (Pytest)
        run: |
          pytest src/backend/python/tests \
            --cov=src/backend/python/app \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=90
        continue-on-error: false
      
      # Step 6: 安全掃描 (Bandit)
      - name: Security scan (Bandit)
        run: |
          bandit -r src/backend/python/app -f json -o bandit-report.json
        continue-on-error: true  # Warning 允許
      
      # Step 7: 上傳覆蓋率報告
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: python
          name: python-coverage

  # ===== 前端 TypeScript + React =====
  frontend-typescript:
    runs-on: ubuntu-latest
    name: "Frontend (TypeScript)"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'src/frontend/package-lock.json'
      
      # Step 1: 安裝依賴
      - name: Install dependencies
        run: |
          cd src/frontend
          npm ci
      
      # Step 2: 代碼格式檢查 (Prettier)
      - name: Check code formatting (Prettier)
        run: |
          cd src/frontend
          npm run format:check
        continue-on-error: false
      
      # Step 3: Lint 檢查 (ESLint) - Strict Mode
      - name: Lint check (ESLint) - Strict
        run: |
          cd src/frontend
          npm run lint
        continue-on-error: false
      
      # Step 4: 類型檢查 (TypeScript strict)
      - name: Type check (TypeScript) - Strict
        run: |
          cd src/frontend
          npx tsc --noEmit --strict
        continue-on-error: false
      
      # Step 5: 單元測試 + 覆蓋率 (Vitest)
      - name: Run tests with coverage (Vitest)
        run: |
          cd src/frontend
          npm run test:coverage
        continue-on-error: false
      
      # Step 6: 依賴安全檢查 (npm audit)
      - name: Security scan (npm audit)
        run: |
          cd src/frontend
          npm audit --audit-level=moderate
        continue-on-error: true  # Warning 允許
      
      # Step 7: 構建檢查
      - name: Build check
        run: |
          cd src/frontend
          npm run build
        continue-on-error: false
      
      # Step 8: 上傳覆蓋率報告
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./src/frontend/coverage/coverage-final.json
          flags: typescript
          name: typescript-coverage

  # ===== 後端 C# + .NET =====
  backend-csharp:
    runs-on: windows-latest
    name: "Backend (C# .NET)"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Step 1: 恢復依賴
      - name: Restore NuGet packages
        run: |
          cd src\backend\csharp
          dotnet restore
      
      # Step 2: 代碼格式檢查 (Roslyn Formatter)
      - name: Check code formatting (Roslyn)
        run: |
          cd src\backend\csharp
          dotnet format --verify-no-changes --verbosity diagnostic
        continue-on-error: false
      
      # Step 3: 構建 + 分析 (StyleCop embedded)
      - name: Build with StyleCop
        run: |
          cd src\backend\csharp
          dotnet build --configuration Release /p:EnforceCodeStyleInBuild=true
        continue-on-error: false
      
      # Step 4: 單元測試 + 覆蓋率
      - name: Run tests with coverage (xUnit)
        run: |
          cd src\backend\csharp
          dotnet test --configuration Release `
            /p:CollectCoverage=true `
            /p:CoverageThreshold=85 `
            /p:FailOnAverageCoverage=true
        continue-on-error: false
      
      # Step 5: 安全分析 (Roslyn Security Analyzers)
      - name: Security analysis
        run: |
          cd src\backend\csharp
          dotnet build --configuration Release /p:AnalysisLevel=latest
        continue-on-error: true  # Warning 允許

  # ===== 通用檢查 =====
  cross-stack-checks:
    runs-on: ubuntu-latest
    name: "Cross-Stack Checks"
    
    steps:
      - uses: actions/checkout@v4
      
      # 檢查文件編碼
      - name: Check file encodings
        run: |
          # 確保所有 YAML 是 UTF-8
          for file in $(find . -name "*.yml" -o -name "*.yaml"); do
            file_encoding=$(file -bi "$file" | awk -F'charset=' '{print $2}')
            if [[ "$file_encoding" != "utf-8" ]]; then
              echo "❌ File $file is not UTF-8 encoded"
              exit 1
            fi
          done
        continue-on-error: false
      
      # 檢查 .editorconfig 一致性
      - name: Validate .editorconfig
        run: |
          [ -f .editorconfig ] && echo "✅ .editorconfig found" || echo "⚠️ No .editorconfig"
      
      # 檢查 git 簽名（可選）
      - name: Validate repository structure
        run: |
          echo "✅ Repository structure valid"

  # ===== 結果匯總 =====
  ci-result:
    name: "CI Result Summary"
    runs-on: ubuntu-latest
    needs: [backend-python, frontend-typescript, backend-csharp, cross-stack-checks]
    if: always()
    
    steps:
      - name: Check CI status
        run: |
          if [ "${{ needs.backend-python.result }}" != "success" ] || \
             [ "${{ needs.frontend-typescript.result }}" != "success" ] || \
             [ "${{ needs.backend-csharp.result }}" != "success" ] || \
             [ "${{ needs.cross-stack-checks.result }}" != "success" ]; then
            echo "❌ CI 檢查失敗"
            echo "請查看上方的詳細錯誤信息"
            exit 1
          else
            echo "✅ 所有 CI 檢查通過！"
          fi
